### ISSUE TITLE
Submit Version 2.0.2 to REDCap repository

### ISSUE THREAD

**Issue by biggeeves** [ctsit/data_driven_project_banner#23]
If the release tagged 2.0.2 is ready for release, could it be submitted to REDCap repo.

**Comment by mmcev106** [comment]
Correct.  We do generally disallow any code allowing user input to be processed as SQL.  Would there be a way to break the user input down into discrete fields that could then be used to build the necessary SQL programmatically?

**Comment by pbchase** [comment]
> Correct. We do generally disallow any code allowing user input to be processed as SQL. Would there be a way to break the user input down into discrete fields that could then be used to build the necessary SQL programmatically?

Nope.

Here's my actual production query that shows how challenging that would be:

```sql
service_identifier, service_type_code, invoice_number, ili.status, amount_due, created, project_id
FROM invoice_line_item as ili
LEFT JOIN redcap_projects as rcp ON (service_identifier = project_id)
WHERE
rcp.project_id = [project_id] AND
ili.service_type_code = 1 AND
ili.status = "invoiced" AND
datediff(now(), ili.created) > 45
limit 1;
```

I'm going to close this. sorry, peeps

**Comment by mmcev106** [comment]
@pbchase, @biggeeves, & @ChemiKyle,

I've since discussed similar user cases with a few other module authors in more detail.  I'm planning a "user supplied query" feature in the next couple of months that would allow this.  I'll add a note to my TODO list to notify you when the initial version of it is ready.  I'd love your input on it.
